[project]
name = "jimmy"
version = "0.0.1"
description = "Implementations of popular vision models in Jax (Flax NNX)"
license = "MIT"
readme = "README.md"

[tool.poetry]
name = "jimmy"
version = "0.0.1"
description = "Implementations of popular vision models in Jax (Flax NNX)"
authors = ["clementpoiret <poiret.clement@outlook.fr>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jax = "^0.4.25"
jaxlib = "^0.4.25"
flax = "^0.8.5"
py7zr = "^0.21.1"
urllib3 = "^2.2.2"
einops = "^0.8.0"

# Needed if one wants to convert weights from pytorch
torch = { version = "^2.3.1", optional = true }
torchvision = { version = "^0.18.1", optional = true }

[tool.poetry.extras]
torch = ["torch", "torchvision"]

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
jimmy = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
